title: Seah Ying Xiang | seahyx.github.io
email: seahyx@gmail.com
github_username: seahyx
github: https://github.com/seahyx/seahyx.github.io
description: HTML, CSS, JS, TS, Flask, Flutter, Java, Python, C++, C#, Lua, Dart, and (My)SQL. Hopefully of use when aliens invade. 👽
baseurl: '/'
url: 'localhost:4000'

google_site_verification: rcn0W-VkKUx63rQ2laiQ8rV2nbHcoeB8z0htPVaTmR4

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
