title: seahyx's website
author:
  name: Seah Ying Xiang
  email: seahyx@gmail.com
github_username: seahyx
github: https://github.com/seahyx/seahyx.github.io
description: Software developer. Hopefully of use when aliens invade. 👽
baseurl: '/'
url: 'localhost:4000'

google_site_verification: rcn0W-VkKUx63rQ2laiQ8rV2nbHcoeB8z0htPVaTmR4

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    github: seahyx

# My theme
remote_theme: seahyx/this-theme

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap
  - jekyll-remote-theme